mysqlHost: 'localhost'
mysqlPort: 3306
mysqlUsername: 'root'
mysqlPassword: '1234567890'
mysqlDatabaseName: 'buildtheword'
pluginPrefix: '&7[&bBTW&7] '
minimumPlayers: 2
buildingDuration: 60
buildingEndDuration: 10
spawnLocation:
  world: 'world'
  x: 0.5
  y: 103.0
  z: -17.5
  yaw: 0.0
  pitch: 0.0
builderSpawnLocation:
  world: 'world'
  x: 0.5
  y: 103.0
  z: 0.5
  yaw: 180.0
  pitch: 0.0